### ISSUE TITLE
Enhance "Solve Large Analysis With Known OD Pairs" tool to do many-to-many problems and accept a table of OD pairs

### ISSUE THREAD

**Issue by dgraham5** [Esri/large-network-analysis-tools#25] opened 2022-12-02 23:31 UTC
First GitHub issue report. Please excuse any GitHub contributing guidelines faux pas...

I am executing the "Solve Large Analysis With Known OD Pairs" tool via a Python script. The script does the following:

1. Reads an input OD Pairs csv file with 6 required variables: Origin_ID, Origin_Longitude, Origin_Latitude, Destination_ID, Destination_Longitude, Destination_Latitude
2. Creates two layers as required by the tool: (1) Origins (Origin_ID, Origin_Longitude, Origin_Latitude, Destination_ID; unique on the combination of Origin_ID and Destination_ID); and (2) Destinations (Destination_ID, Destination_Longitude, Destination_Latitude; unique on Destination_ID).
3. Executes the tool given user inputs and using the layers created in Step 2
4. Does a table-to-table conversion on the output layer to return a CSV file with the calculated travel metrics merged onto a copy of the original file

However, I am encountering an unexpected error at step 3 when attempting to execute the tool. Specifically:

*arcgisscripting.ExecuteError: Non-unique values were found in the unique ID field Origin_ID in <MappingLayerObject object at 0x0000026C2BE445E0>.
Invalid inputs.
Failed to execute (SolveLargeAnalysisWithKnownPairs).*

This error message is surprising to me: the origins in the Origins input layer -- and hence the Origin_ID values -- are expected to be non-unique given the requirement to include for each origin the set of assigned destinations. Right? Or should I read the following literally to say that each origin can only be assigned a single destination:

*Assigned Destination Field (Python: Assigned_Destination_Field) - A field in origins indicating the ID of the destination each origin is assigned to. Any origin with a null value or a value that does not match a valid destination ID will be ignored in the analysis.*

If that's the case, no issue per se, but it would be helpful if the tool were generalized to accept a list of OD pairs. Each pair unique on the combination of origin ID and destination ID, but not necessarily on either individually.

P.S. if this does in fact turn out to be a question of functionality rather than an issue, here's my minor issue contribution: the GitHub landing page for large-network-analysis-tools (https://github.com/Esri/large-network-analysis-tools) has a minor oversight in the "Solve Large Analysis With Known OD Pairs tool" section. The tool signature under the "Running the tool from standalone Python" subsection references the right arguments but the wrong function: "arcpy.LargeNetworkAnalysisTools.SolveLargeODCostMatrix" rather than "arcpy.LargeNetworkAnalysisTools.SolveLargeAnalysisWithKnownPairs" as above.

Thank you in advance!

**Comment by mmorang** [comment] 2022-12-03 00:15
Hmm, I see what you're saying.

As currently implemented, the tool requires two separate layers as inputs - origins and destinations.  Currently the assumption is that each input in the origins is assigned to one specific destination (one-to-one).  You are trying to do a many-to-many problem with specifically assigned pairs, and the tool isn't really set up to do that.

However, your input data already has the origins exploded out with copies of all the origins and destinations, it seems like.  To make it work with the existing tool, here's what I think you should do:
1. For your origins, after creating the layer, you'll have duplicates, but that's okay because you want these.  Just create a new field to use as the unique ID for the analysis and populate it with unique values.
2. For your destinations, delete all rows with duplicate ID values.  You only need one copy of each destination.
3. Run the tool using the new origin unique ID field.  It should work.
4. Post-process to map the new origin unique IDs back to your original Origin_ID values if necessary.

Thanks for noticing that typo/copy-paste error in the readme. I'll get that fixed.

**Comment by dgraham5** [comment] 2022-12-03 00:25
That makes sense. Thank you for the prompt explanation. I will code a workaround along the lines you describe. Btw, your step 2 is totally right -- I should have mentioned that I dedup the destinations layer after creating it using the exploded dataset.

Is it difficult to configure the tool to permit one-to-many and many-to-many matches? Rightly or wrongly, it's what I expected the functionality to be -- it seems a natural generalization of the actual functionality. Most often what I'm looking to do is calculate distances from a set of origins to, for each origin, a set of one or more (often more) destinations. Maybe something I can explore via a fork.

**Comment by mmorang** [comment] 2022-12-05 15:46
Yes, I think this would be a good enhancement.  I think the UI would need to include the following parameters:
- Origin locations
- Origins Unique ID field
- Destination locations
- Destinations Unique ID field
- Table/csv containing origin/destination pairs
(Probably, to support both the existing situation and this new case, I would have a switcher parameter for the different modes that would alter the available parameters.)

Internally, it wouldn't be horrifically difficult to implement.  It just requires a close look at the chunking logic and slight changes in loading the inputs.

I will put this on my to-do list for the next time my plate is cleared enough to get to it.

**Comment by dgraham5** [comment] 2022-12-05 16:07
Much appreciated!

For what it's worth, I don't think the switcher parameter would be necessary -- wouldn't one destination per origin be a specific case of the general multiple destinations per origin logic?

Also, out of curiosity, any insight into whether an ODCM object/solver or Route object/solver would be faster for this? In my script, I had relied on the Route Solver since it seemed better suited to handling origin-destination pairs.

**Comment by mmorang** [comment] 2022-12-05 16:13
Yeah, unfortunately, the OD solver just doesn't do preassigned pairs, so you pretty much have to use Route.  The only way you could use OD is if you chunked it up so that each chunk had a single origin and all the destinations assigned to it.  That might be an efficient way to chunk if the number of destinations per origin is large, but otherwise it's probably just easier to use Route.

In general, OD is faster than Route, and it includes more optimizations for memory management for very large problems.  So, if the problem is suited to OD, it's better to use OD.  Just doesn't quite work for this use case.

You might be right about the switcher parameter.  I think it depends on how people have their data set up.  If the tool can support more than one input data situation, it will be more convenient to users, so it might be worth having both options.  Anyway, I will give it some thought when time allows.

I'm going to leave this issue open but will change the title to reflect the requested enhancement.

**Comment by dgraham5** [comment] 2022-12-05 16:16
Awesome, thank you :)

**Comment by mmorang** [comment] 2023-01-06 22:58
The updates have been merged.  Please let me know how this works for your needs and if you encounter any problems.

**Closed** 2023-01-06 22:58 UTC

**Comment by dgraham-cra** [comment] 2023-01-14 18:29
Hi Melinda,

Thank you! I haven't had the opportunity to test the new and improved tool yet, but I appreciate the enhancement :)

Thank you for being responsive and open to making changes.

Best,
Duncan

**Comment by mmorang** [comment] 2023-04-04 21:35
Hello @dgraham5.  Hope the many-to-many version of the tool worked out for you.

Esri’s Network Analyst Team is doing some research about customer workflows involving solving routes or calculating travel times and distances between known or preassigned pairs of origins and destinations.  We’d like to better understand our customers’ needs in this area and may use this information to design and develop improved tools and workflows.

If you have a few minutes and are willing, could you please fill out the attached survey and return it to the e-mail address included inside the document?  Alternatively, you can reach out to me (my e-mail address is in the document) to set up a meeting.

Thank you so much!!
[UserQuestionnaire_PreassignedODPairs.docx](https://github.com/Esri/large-network-analysis-tools/files/11153469/UserQuestionnaire_PreassignedODPairs.docx)
